plugins {
    id 'com.android.application'
}

android {
    namespace 'com.sreehitha.ideawalk'
    compileSdk 34

    defaultConfig {
        applicationId 'com.sreehitha.ideawalk'
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }

    signingConfigs {
        release {
            storeFile file('ideawalk.keystore')
            storePassword 'ideawalk-keystore'
            keyAlias 'ideawalk'
            keyPassword 'ideawalk-keystore'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }

    lint {
        checkReleaseBuilds false
        abortOnError false
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
